# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e2d2d5829f1e1b3fbc6bc2d4ec4990c3c4f6c76b2ff9f9c46e6bbbb52c5840864d570796df5460b2048f55392834946685d238eb089598ef712c69000523df5

test:
  secret_key_base: c6572836cb8b3316256d274a682b3c4bafa59938d67ff8ff9e4a608e8513706c7b5039184d76efe0dff1ba0d459a7e2c9fe58bfd0fe9a07e0f421198a8d11b83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
